import Head from 'next/head';
import Link from 'next/link';
import { StockMarketDetailContext } from '@/layout/main-layout';

import styles from '@/styles/common.module.css';

import type { ScanItem } from '@/layout/main-layout';

type propsScanItem = {
  id: ScanItem['id'];
  name: ScanItem['name'];
  tag: ScanItem['tag'];
  color: ScanItem['color'];
};
function ScanItem({ id, name, tag, color }: propsScanItem) {
  return (
    <li>
      <Link href={`/details/${id}`} >
        <div className="flex items-center px-4 py-4 sm:px-6">
          <div className="min-w-0 flex-1 sm:flex sm:items-center sm:justify-between">
            <div className="truncate">
              <div className="flex">
                <p className="truncate font-medium text-indigo-600">{name}</p>
              </div>
            </div>
          </div>
          <div className="ml-16 flex flex-shrink-0">
            <p className={styles[`tag-${color}`]}>
              {tag}
            </p>
          </div>
          <div className="ml-5 flex-shrink-0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="h-5 w-5 text-gray-400"><path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5"></path></svg>
          </div>
        </div>
      </Link>
    </li>
  );
}

export default function Scan() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex items-center justify-between border-t border-gray-200 bg-gray-100  px-4 py-3 sm:px-6" >
        <StockMarketDetailContext.Consumer>
          {(details) => {
            console.log("Scan", details);
            return (
              <div className='overflow-hidden bg-white shadow sm:rounded-md mx-auto max-w-md md:min-w-[40vw]' >
                <ul role="list" className='divide-y divide-gray-200' >
                  {details.map((scan) => (<ScanItem key={scan.id} id={scan.id} name={scan.name} tag={scan.tag} color={scan.color} />))}
                </ul>
              </div>
            );
          }}
        </StockMarketDetailContext.Consumer>
      </main>
    </>
  )
}
